version: '3.1'

services:

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: bookstore
      MARIADB_USER: user
      MARIADB_PASSWORD: user-password
      MARIADB_ROOT_PASSWORD: user-password
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
